const KEY="premium-workspace-v1";const defaultState={visits:0,actions:0,premium:false,events:[],accountValue:0};let state=JSON.parse(localStorage.getItem(KEY)||"null")||defaultState;state.visits++;save();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];function save(){localStorage.setItem(KEY,JSON.stringify(state))}
const events=[
["SUBSCRIPTION UPDATED","Amount charged: ₹999.<br>Product purchased: <b>Unknown</b>.<div class='chaos'>Your billing profile is being synchronized across services.</div>"],
["BILLING REVIEW","Reason: <b>The payment provider requested another verification step.</b><div class='chaos'>Please try again using a more financially motivated bank account.</div>"],
["SUBSCRIPTION UPDATED","You have been charged <b>₹0</b>.<br>Your service adjustment is ₹17,492.<div class='chaos'>Emotional fees are non-refundable because feelings are complicated.</div>"],
["PROCESSING","Estimated completion: <b>the next billing cycle</b>.<div class='chaos'>Our calendar has been escalated to management.</div>"],
["PREMIUM POTATO™","You have unlocked advanced analytics, expanded storage and intelligent assistance.<div class='chaos'>Your workspace package has been queued for provisioning.</div>"],
["PREMIUM CHAIR™","You can now work with improved ergonomics.<div class='chaos'>Ergonomic confidence has been enabled.</div>"],
["PREMIUM AIR™","You've unlocked additional capacity.<div class='chaos'>Additional capacity is available on Enterprise.</div>"],
["CORPORATE UPDATE","Your account role has changed.<div class='chaos'>Contact your administrator to review permissions.</div>"],
["CONGRATULATIONS","You've been promoted to <b>Senior Vice President of Premium Purchasing</b>.<br>Salary: ₹0<br>Responsibilities: Everything<div class='chaos'>Resignation is a Premium feature.</div>"],
["SYSTEM NOTICE","This button wasn't supposed to work.<div class='chaos'>Please pretend you didn't see this.</div>"],
["AI STATUS","I asked another AI. It asked another AI. That AI asked ChatGPT. Nobody knows.<div class='chaos'>The AI has resigned.</div>"],
["SUBSCRIPTION UPDATED","Order #847291847291847291<br>Delivery: Not Applicable<br>Refund: Also Not Applicable<br>Cancellation: Currently under review<div class='chaos'>Thank you for your cooperation. Please close this window. This window will not close.</div>"],
["FINANCIAL UPDATE","Your account balance: ₹0<br>Your subscription: ₹9,99,999/month<br>Your subscription status: Active<br>Your payment status: Successful<div class='chaos'>Your account status: <b>Pending review</b> Please contact your account administrator.</div>"],
["PREMIUM ENLIGHTENMENT","You have unlocked the ability to understand Premium.<div class='chaos'>Unfortunately, understanding Premium has been discontinued.</div>"]
];
const activityPool=["Opened a workspace feature","Reviewed billing","Used AI assistance","Updated account settings","Optimized workspace","Viewed product details","Updated account role","Updated subscription","Viewed enterprise options"];
function addActivity(t){state.events.unshift(t);state.events=state.events.slice(0,4);save();renderActivity()}function renderActivity(){const f=$("#activityFeed");f.innerHTML=state.events.map((e,i)=>`<div class="activity-row"><b>${e}</b><span>${i===0?"just now":i+"m ago"}</span></div>`).join("")||"<div class='activity-row'><b>Account created</b><span>just now</span></div>"}renderActivity();
$("#accountValue").textContent="₹"+(state.accountValue||0).toLocaleString("en-IN");$("#premiumStatus").textContent=state.premium?"Premium Active":"Free Preview";$("#happiness").textContent=(98+Math.random()*1.9).toFixed(1)+"%";
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove("show"),2800)}
function confetti(){const c=$("#confetti");c.innerHTML="";for(let i=0;i<70;i++){const p=document.createElement("i");p.className="piece";p.style.left=Math.random()*100+"%";p.style.top=(-Math.random()*20)+"%";p.style.background=["#5b5bf7","#17a673","#111318","#ffbd2e","#ff6158"][Math.floor(Math.random()*5)];p.style.animationDelay=Math.random()*.5+"s";c.appendChild(p)}setTimeout(()=>c.innerHTML="",1800)}
function randomEvent(){return events[Math.floor(Math.random()*events.length)]}
function openModal(title,body,actions=""){const m=$("#modalBackdrop");$("#modalContent").innerHTML=`<h2>${title}</h2><p>${body}</p>${actions}`;m.classList.add("open");m.setAttribute("aria-hidden","false")}
function closeModal(){$("#modalBackdrop").classList.remove("open");$("#modalBackdrop").setAttribute("aria-hidden","true")}
function upgrade(){state.actions++;addActivity(activityPool[Math.floor(Math.random()*activityPool.length)]);const [t,b]=randomEvent();if(Math.random()<.35){state.premium=true;state.accountValue+=999;save();$("#premiumStatus").textContent="Premium Active";confetti()}openModal(t,b,`<div class="modal-actions"><button class="secondary" id="modalAgain">Try Again</button><button class="primary" id="modalAccept">${state.premium?"Continue":"Upgrade anyway"} →</button></div>`);$("#modalAgain").onclick=()=>{closeModal();setTimeout(upgrade,180)};$("#modalAccept").onclick=()=>{closeModal();toast(["Congratulations. Your mistake has been processed.","Welcome to Premium. Your subscription details are available in Billing.","Your request has been routed to the appropriate team."][Math.floor(Math.random()*3)]);if(Math.random()<.3)setTimeout(()=>openModal("WAIT.","Why did you click that?<div class='chaos'>This interaction has been forwarded to the Board.</div>","<div class='modal-actions'><button class='primary' id='board'>Acknowledge</button></div>"),700);$("#board")?.addEventListener("click",closeModal)}}
function action(type){if(type==="upgrade"||type==="start"){upgrade();return}if(type==="login"){openModal("Sign in","Enter your credentials to continue. <div class='chaos'>Use your work email and password to continue.</div>","<div class='modal-actions'><button class='primary' id='mystery'>Continue</button></div>");$("#mystery").onclick=()=>{closeModal();toast("Authentication successful. Your session is ready.")};return}if(type==="demo"){openModal("Premium Demo","Your personalized demo is being prepared.","<div class='modal-actions'><button class='primary' id='wait'>Wait patiently</button></div>");$("#wait").onclick=()=>{closeModal();toast("Demo scheduled for your next available session.")};return}if(type==="ai"){openModal("PremiumGPT™","Ask anything. We may answer, upgrade you, or ask another AI.<div class='chaos'>Current model: Premium Intelligence v4.7</div>","<div class='modal-actions'><button class='primary' id='ask'>Ask a question</button></div>");$("#ask").onclick=()=>{closeModal();setTimeout(()=>openModal("PremiumGPT™","That's an excellent question.<br><br><b>I need a little more context to answer that.</b><div class='chaos'>Advanced responses are available with Premium Intelligence.</div>","<div class='modal-actions'><button class='primary' id='aiup'>Upgrade →</button></div>"),350)};$("#aiup")?.addEventListener("click",()=>{closeModal();upgrade()});return}if(type==="speed"){const n=Math.floor(Math.random()*900+100);openModal("Quantum Performance",`Your workspace response time was ${n} ms.<div class='chaos'>Performance monitoring has recorded an excellent result.</div>`);addActivity("Tested quantum performance");return}if(type==="security"||type==="audit"){addActivity("Ran enterprise security audit");openModal("Security Audit","Security score: <b>100/100</b><br>Threats detected: 0<br>Policy checks completed: 14<div class='chaos'>The security operations team has been notified.</div>");return}if(type==="enterprise"){openModal("Enterprise Sales","Our sales team has been notified.<div class='chaos'>Expected response: <b>within 1 business day.</b></div>");addActivity("Viewed enterprise options");return}if(type==="free"){const choices=["Interesting choice.","Your current plan remains active.","Your accountant is proud.","We will remember this.","Your current plan has been saved."];toast(choices[Math.floor(Math.random()*choices.length)]);addActivity("Chose Free");return}}
$$("[data-action]").forEach(b=>b.addEventListener("click",()=>action(b.dataset.action)));$("#modalClose").onclick=closeModal;$("#modalBackdrop").addEventListener("click",e=>{if(e.target.id==="modalBackdrop")closeModal()});$("#announcementClose").onclick=()=>{$(".announcement").style.display="none";toast("Announcement hidden. Premium visibility remains enabled.")};
setInterval(()=>{$("#lastChecked").textContent=["just now","a few seconds ago","2 milliseconds ago","before you arrived"][Math.floor(Math.random()*4)]},4000);
if(state.visits>1&&Math.random()<.55)setTimeout(()=>toast(["Welcome back. We noticed.","Your Premium journey continues.","We remember your financial decisions.","You returned. Interesting."][Math.floor(Math.random()*4)]),1800);
window.addEventListener("beforeunload",()=>{if(Math.random()<.18)localStorage.setItem(KEY,JSON.stringify({...state,events:[...state.events,"Updated account settings"]}))});